version: "3.7"

services:
  selenium_chrome:
    image: selenium/standalone-chrome:latest
    container_name: bewtest-selenium-chrome
    ports:
      - 4444:4444
      - 7900:7900
    build:
      context: .
      shm_size: '2gb'
  bewtest-app:
    image: bewtest:latest
    container_name: bewtest-app
    build:
      context: .
    ports:
      - 25:25
      - 80:80
      - 8888:8888
    depends_on:
      - "selenium_chrome"
    volumes:
      - /home/peterk776/dev/bewtest/config:/opt/piag/bewtest
volumes:
  data:
