version: "3.7"

services:
  selenium_chrome:
    image: selenium/standalone-chrome:latest
    container_name: bewtest-selenium-chrome
    ports:
      - 4444:4444
      - 7900:7900
    build:
      context: .
      shm_size: '2gb'
    dns: 
      - 192.168.1.61
  bewtest-app:
    image: bewtest:latest
    container_name: bewtest-app
    build:
      context: .
    dns: 
      - 192.168.1.61
    ports:
      - 8888:8888
    depends_on:
      - "selenium_chrome"
    volumes:
      - /dev/gcloud/bewtest:/opt/piag/bwetest
volumes:
  data:
